# Generated by Django 3.1.4 on 2020-12-01 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text='Имя БФП', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_id', models.CharField(max_length=200)),
                ('port', models.IntegerField(help_text='Port в диапазоне 30.000 - 32.000')),
                ('proxy_name', models.CharField(help_text='Имя отключаемой прокси', max_length=50)),
                ('time_to_stop', models.DateTimeField(blank=True, null=True)),
                ('time_to_start', models.DateTimeField(blank=True, null=True)),
                ('Projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy_master.projects')),
            ],
        ),
    ]
