# Generated by Django 3.1.4 on 2020-12-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_master', '0002_projects_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='author',
            new_name='Author',
        ),
    ]
