# Generated by Django 3.1.4 on 2020-12-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_master', '0004_auto_20201201_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='Projects',
            new_name='projects',
        ),
    ]
