# Generated by Django 3.1.4 on 2020-12-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_master', '0005_auto_20201201_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='id',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
