# Generated by Django 3.1.4 on 2020-12-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_master', '0006_auto_20201201_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
