# Generated by Django 3.1.4 on 2020-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_master', '0007_auto_20201201_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='proxy_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
