# Generated by Django 3.1.4 on 2020-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_master', '0008_auto_20201201_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='staticParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_path', models.CharField(help_text='Путь до бинарника proxy', max_length=50)),
                ('proxy_type', models.CharField(default='tcp', help_text='тип прокси', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='port',
        ),
        migrations.AddField(
            model_name='proxy',
            name='author',
            field=models.CharField(default='eg', help_text='Имя автора ', max_length=50),
        ),
        migrations.AddField(
            model_name='proxy',
            name='fp_name',
            field=models.CharField(default='ololo', help_text='FP_name', max_length=50),
        ),
        migrations.AddField(
            model_name='proxy',
            name='protocol',
            field=models.CharField(default='TCP', help_text='Протокол создаваемой прокси', max_length=50),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_port',
            field=models.IntegerField(default=0, help_text='Port в диапазоне 30.000 - 32.000'),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_status',
            field=models.BooleanField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='time_to_start',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='time_to_stop',
            field=models.DateTimeField(blank=True),
        ),
    ]
