# Generated by Django 3.1.4 on 2020-12-13 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_master', '0010_auto_20201213_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='time_to_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 18, 59, 17, 172850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='time_to_stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 18, 59, 17, 172808, tzinfo=utc)),
        ),
    ]
